name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Checkout Repo code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies and Generate Report
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage pytest
        python -m pytest tests/ 
        coverage run -m pytest tests/
        coverage report
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      
